//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingsManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializationExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializationExceptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SettingsManager.Resources.SerializationExceptionStrings", typeof(SerializationExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object to serialize contains a complex data structure which can not be serialized..
        /// </summary>
        internal static string ComplexDataStructure {
            get {
                return ResourceManager.GetString("ComplexDataStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple fields/properties have been assigned the name &apos;{0}&apos; using the PlainTextElement attribute..
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header that was read had an incorrect format..
        /// </summary>
        internal static string HeaderFormat {
            get {
                return ResourceManager.GetString("HeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object string &apos;{0}&apos; could not be converted to the type &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidObjectString {
            get {
                return ResourceManager.GetString("InvalidObjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given object is not a class type. Only classes with fields/properties can be serialized..
        /// </summary>
        internal static string InvalidSerializationType {
            get {
                return ResourceManager.GetString("InvalidSerializationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property on line &apos;{0}&apos; has an incorrect format..
        /// </summary>
        internal static string InvalidSettingFormat {
            get {
                return ResourceManager.GetString("InvalidSettingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the field/property can not contain any comments..
        /// </summary>
        internal static string NameContainedComment {
            get {
                return ResourceManager.GetString("NameContainedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; can not be serialized because it does not have a public setter..
        /// </summary>
        internal static string NoPublicSetter {
            get {
                return ResourceManager.GetString("NoPublicSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property could not be read as it did not contain the property separator : &apos;{0}&apos;..
        /// </summary>
        internal static string PropertyMissingSeparator {
            get {
                return ResourceManager.GetString("PropertyMissingSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property could not be deserialized as its name was not specified..
        /// </summary>
        internal static string PropertyNameEmpty {
            get {
                return ResourceManager.GetString("PropertyNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property with the name &apos;{0}&apos; could not be deserialized as it did not have its value specified..
        /// </summary>
        internal static string PropertyValueEmpty {
            get {
                return ResourceManager.GetString("PropertyValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; could not be decoded by the decoder..
        /// </summary>
        internal static string TypeCouldNotBeDecoded {
            get {
                return ResourceManager.GetString("TypeCouldNotBeDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; can not be serialized because it has no parameterless constructor..
        /// </summary>
        internal static string TypeHasNoParameterlessConstructor {
            get {
                return ResourceManager.GetString("TypeHasNoParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; can not be serialized because it is not public..
        /// </summary>
        internal static string TypeNotAccessible {
            get {
                return ResourceManager.GetString("TypeNotAccessible", resourceCulture);
            }
        }
    }
}
